services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - "9200:9200" # 外部通信使用
      - "9300:9300" # 内部node节点通信
    environment:
      - discovery.type=single-node #单节点
      - xpack.security.enabled=false #不使用 https
    networks:
      - es
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    ports:
      - "5601:5601"
    environment:
      - I18N_LOCALE=zh-CN #中文
      - XPACK_GRAPH_ENABLED=true # 启用X-Pack插件的图形功能，该插件提供了图形分析和可视化功能
      - TIMELION_ENABLED=true # 启用Timelion插件，它是一个用于时间序列数据分析和可视化的插件
      - XPACK_MONITORING_COLLECTION_ENABLED="true" # 启用X-Pack监控插件的数据收集功能，用于监控Kibana的性能和运行情况
    networks:
      - es
networks:
  es:
    driver: bridge